version: "3.8"

services:
  # üåê Frontend alcaldiafetch - QA
  alcaldiafetch-front-qa:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    ports:
      - "4201:${PORT}"
    restart: always
    env_file:
      - .env
    networks:
      - network_qa
    labels:
      - com.alcaldiafetch.environment=qa

networks:
  network_qa:
    driver: bridge
