version: "3.8"

services:
  # üåê Frontend alcaldiafetch - STAGING
  alcaldiafetch-front-staging:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    ports:
      - "4202:${PORT}"
    restart: always
    env_file:
      - .env
    networks:
      - network_staging
    labels:
      - com.alcaldiafetch.environment=staging

networks:
  network_staging:
    driver: bridge
